//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QGS.Entities.DataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbQGSVLEntities : DbContext
    {
        public DbQGSVLEntities()
            : base("name=DbQGSVLEntities")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<tblBankDetail> tblBankDetails { get; set; }
        public virtual DbSet<tblContractType> tblContractTypes { get; set; }
        public virtual DbSet<tblDocument> tblDocuments { get; set; }
        public virtual DbSet<tblDocumentType> tblDocumentTypes { get; set; }
        public virtual DbSet<tblDriver> tblDrivers { get; set; }
        public virtual DbSet<tblEmployementDetail> tblEmployementDetails { get; set; }
        public virtual DbSet<tblEmployementStatu> tblEmployementStatus { get; set; }
        public virtual DbSet<tblEquipment> tblEquipments { get; set; }
        public virtual DbSet<tblIncludedService> tblIncludedServices { get; set; }
        public virtual DbSet<tblInsurance> tblInsurances { get; set; }
        public virtual DbSet<tblMaritalStatu> tblMaritalStatus { get; set; }
        public virtual DbSet<tblMileage> tblMileages { get; set; }
        public virtual DbSet<tblNationality> tblNationalities { get; set; }
        public virtual DbSet<tblPaybackTime> tblPaybackTimes { get; set; }
        public virtual DbSet<tblPropertyStatu> tblPropertyStatus { get; set; }
        public virtual DbSet<tblQuote> tblQuotes { get; set; }
        public virtual DbSet<tblRentDetail> tblRentDetails { get; set; }
        public virtual DbSet<tblRoleManagement> tblRoleManagements { get; set; }
        public virtual DbSet<tblStatu> tblStatus { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblVehicleDetail> tblVehicleDetails { get; set; }
    }
}
