//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QGS.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblBankDetail
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> QuoteId { get; set; }
        public string IBAN { get; set; }
    
        public virtual tblQuote tblQuote { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
