//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QGS.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocument
    {
        public int Id { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<int> QuoteId { get; set; }
    
        public virtual tblDocumentType tblDocumentType { get; set; }
        public virtual tblQuote tblQuote { get; set; }
    }
}
