//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QGS.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipment
    {
        public int EqId { get; set; }
        public Nullable<int> CarId { get; set; }
        public string EquipmentType { get; set; }
        public string Features { get; set; }
    
        public virtual tblVehicleDetail tblVehicleDetail { get; set; }
    }
}
