//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QGS.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployementDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EmployementStatus { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> ContractType { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> PostCode { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual tblContractType tblContractType { get; set; }
        public virtual tblEmployementStatu tblEmployementStatu { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
