//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QGS.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIncludedService
    {
        public int IsId { get; set; }
        public string ServiceName { get; set; }
    }
}
