//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QGS.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuote()
        {
            this.tblBankDetails = new HashSet<tblBankDetail>();
            this.tblDocuments = new HashSet<tblDocument>();
        }
    
        public int QuoteId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> CarId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> InsuranceId { get; set; }
        public Nullable<int> MileageId { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PaybackTimeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBankDetail> tblBankDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocument> tblDocuments { get; set; }
        public virtual tblInsurance tblInsurance { get; set; }
        public virtual tblMileage tblMileage { get; set; }
        public virtual tblPaybackTime tblPaybackTime { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblVehicleDetail tblVehicleDetail { get; set; }
        public virtual tblStatu tblStatu { get; set; }
    }
}
