//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QGS.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRentDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> NetMonthyIncome { get; set; }
        public Nullable<int> RentalIncome { get; set; }
        public Nullable<int> PropertyStatus { get; set; }
        public Nullable<int> CreditCost { get; set; }
        public Nullable<int> MonthyRent { get; set; }
    
        public virtual tblPropertyStatu tblPropertyStatu { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
