//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QGS.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblBankDetails = new HashSet<tblBankDetail>();
            this.tblDrivers = new HashSet<tblDriver>();
            this.tblEmployementDetails = new HashSet<tblEmployementDetail>();
            this.tblQuotes = new HashSet<tblQuote>();
            this.tblRentDetails = new HashSet<tblRentDetail>();
        }
    
        public int UserId { get; set; }
        public string UserEmail { get; set; }
        public string Password { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Contact { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string isMainDriver { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> RegistrationNumber { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> PostCode { get; set; }
        public string City { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<System.DateTime> LivedSince { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBankDetail> tblBankDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDriver> tblDrivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployementDetail> tblEmployementDetails { get; set; }
        public virtual tblMaritalStatu tblMaritalStatu { get; set; }
        public virtual tblNationality tblNationality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuote> tblQuotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRentDetail> tblRentDetails { get; set; }
        public virtual tblRoleManagement tblRoleManagement { get; set; }
    }
}
