//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QGS.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVehicleDetail()
        {
            this.tblEquipments = new HashSet<tblEquipment>();
            this.tblQuotes = new HashSet<tblQuote>();
        }
    
        public int CarId { get; set; }
        public string Image { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string ModelName { get; set; }
        public string HorsePower_HP_ { get; set; }
        public string Consumption_L_100Km_ { get; set; }
        public string Co2Emission_g_Km_ { get; set; }
        public string FuelType { get; set; }
        public Nullable<int> Seating { get; set; }
        public Nullable<bool> Abs { get; set; }
        public Nullable<int> Airbag { get; set; }
        public string Transmission { get; set; }
        public string Colour { get; set; }
        public Nullable<int> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEquipment> tblEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuote> tblQuotes { get; set; }
    }
}
